---
baseURL: http://miguelpenteado.com.br/
languageCode: pt-br
title: Blog do Miguel Penteado
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: pt-br
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: Profile
  facebook: https://web.facebook.com/pages/n%C3%A3o-tenho/324280494315834
  twitter: https://twitter.com/GoHugoIO
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2
menu:
  main:
  - url: https://www.linkedin.com/in/miguel-penteado-760486a9/
    name: LinkedIn
    weight: 2
